<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.daxpay.open</groupId>
        <artifactId>daxpay-platform-capability</artifactId>
        <version>4.0.0-beta1</version>
    </parent>

    <artifactId>capability-nonce</artifactId>
    <description>防重放Nonce验证</description>

    <dependencies>
        <!-- web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- redis -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <!-- AOP -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aspectj</artifactId>
        </dependency>

        <!-- 认证（@IgnoreAuth注解） -->
        <dependency>
            <groupId>cn.daxpay.open</groupId>
            <artifactId>capability-auth</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- spring配置 -->
        <dependency>
            <groupId>cn.daxpay.open</groupId>
            <artifactId>common-spring</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- 项目配置 -->
        <dependency>
            <groupId>cn.daxpay.open</groupId>
            <artifactId>common-config</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
