<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.daxpay.open</groupId>
        <artifactId>daxpay-platform-capability</artifactId>
        <version>4.0.0-beta3</version>
    </parent>

    <artifactId>capability-wechat</artifactId>
    <description>微信公众号和小程序管理服务</description>

    <dependencies>
        <!-- web容器 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- 核心包 -->
        <dependency>
            <groupId>cn.daxpay.open</groupId>
            <artifactId>daxpay-platform-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- mybatis-plus -->
        <dependency>
            <groupId>cn.daxpay.open</groupId>
            <artifactId>common-mybatis-plus</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- 微信工具包-公众号 -->
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-mp</artifactId>
            <version>${wxjava.version}</version>
        </dependency>
        <!-- 微信工具包-小程序 -->
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-miniapp</artifactId>
            <version>${wxjava.version}</version>
        </dependency>
        <!-- Redis + 分布式锁封装 -->
        <dependency>
            <groupId>cn.daxpay.open</groupId>
            <artifactId>common-redis</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
