spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          # Postgresql连接
          driver-class-name: org.postgresql.Driver
          url: ${DB_URL}
          username: ${DB_USER}
          password: ${DB_PASSWORD}
      hikari:
        keepalive-time: 300000
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      database: 14
      password: ${REDIS_PASSWORD:''}
      lettuce:
        pool:
          max-wait: 1000ms
# 开发时显示debug日志
logging:
  level:
    cn.bootx.**: debug
    cn.daxpay.**: debug
    org.springframework.jdbc.core: debug
# 接口文档配置
springdoc:
  # 默认展开对象类型的属性, 主要用在get类型的参数中
  default-flat-param-object: true
knife4j:
  # 开启接口文档增强特性
  enable: true
  # 是否为生产环境, 为true关闭swagger接口
  production: ${KNIFE4J_PRODUCTION:false}
# 基础脚手架配置
# 基础脚手架配置
bootx-platform:
  common:
    # swagger相关配置
    swagger:
      author: DaxPay
      title: DaxPay支付平台-融合端
      description: DaxPay支付平台-多商户版-融合端
      version: 0.0.1
      base-packages:
        "[BootxPlatform接口]":
          - cn.bootx.platform.common
          - cn.bootx.platform.starter
          - cn.bootx.platform.iam
          - cn.bootx.platform.baseapi
          - cn.bootx.platform.notice
        "[支付平台接口]":
          - org.dromara.daxpay.union
          - org.dromara.daxpay.controller
        "[支付通道接口]":
          - org.dromara.daxpay.channel
  starter:
    auth:
      # 是否启用超级管理员登录
      enable-admin: ${DAXPAY_ENABLE_ADMIN:true}
      # 用户管理列表中是否显示超级管理员
      admin-in-list: ${DAXPAY_ADMIN_IN_LIST:true}
      ignore-urls:
        - '/actuator/**'
        - '/v3/api-docs/**'
        - '/doc.html'
        - '/swagger-resources/**'
        - '/token/**'
        - '/ws/**'
        - '/demo/**'
        - '/test/**'
        - '/webjars/**'
        - '/front/**'
        - '/h5/**'
        - '/css/**'
        - '/error'
        - '/favicon.ico'
    file-upload:
      # 使用后端代理访问, 线上请使用 Nginx 配置或者直连方式，效率更高
      forward-server-url: http://127.0.0.1:9999
    oss:
      file-path: customer_info/
dax-pay:
  env: DEV_
  machine-no: 70
dromara:
  # 注意, 不要设置 domain 访问路径, 自行进行拼接访问路径, 来保证可迁移性
  x-file-storage:
    default-platform: local
    # 使用Nginx映射到存储路径, 然后将nginx的地址设置到 bootx-platform.starter.file-upload.file-server-url参数
    local-plus:
      - platform: local
        enable-storage: true
        base-path: /file/ # 基础路径
        storage-path: /data/files # 存储路径
