spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          # Postgresql连接
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://postgresql:5432/dax-pay-single?serverTimezone=Asia/Shanghai&autoReconnect=true&reWriteBatchedInserts=true
          username: bootx
          password: bootx123
      hikari:
        keepalive-time: 300000
  data:
    redis:
      host: redis
      port: 6379
      database: 5
      password: bootx123
      lettuce:
        pool:
          max-wait: 1000ms
# 开发时显示debug日志
logging:
  level:
    cn.bootx.**: debug
    cn.daxpay.**: debug
    org.springframework.jdbc.core: debug
# 接口文档配置
springdoc:
  # 默认展开对象类型的属性, 主要用在get类型的参数中
  default-flat-param-object: true
# 基础脚手架配置
bootx-platform:
  common:
    # swagger相关配置
    swagger:
      author: DaxPay
      title: DaxPay支付平台
      description: DaxPay支付平台-开源版
      version: 0.0.1
      base-packages:
        "[BootxPlatform接口]":
          - cn.bootx.platform.common
          - cn.bootx.platform.starter
          - cn.bootx.platform.iam
          - cn.bootx.platform.baseapi
          - cn.bootx.platform.notice
        "[支付平台接口]":
          - org.dromara.daxpay.controller
        "[支付通道接口]":
          - org.dromara.daxpay.channel
  starter:
    auth:
      enable-admin: true
      ignore-urls:
        - '/actuator/**'
        - '/v3/api-docs/**'
        - '/doc.html'
        - '/swagger-resources/**'
        - '/token/**'
        - '/ws/**'
        - '/demo/**'
        - '/test/**'
        - '/webjars/**'
        - '/front/**'
        - '/h5/**'
        - '/css/**'
        - '/error'
        - '/favicon.ico'
dax-pay:
  env: DEV_
  machine-no: 70
dromara:
  # 注意, 不要设置 domain 访问路径, 自行进行拼接访问路径, 来保证可迁移性
  x-file-storage:
    default-platform: local
    # 使用Nginx映射到存储路径, 然后将nginx的地址设置到 bootx-platform.starter.file-upload.file-server-url参数
    local-plus:
      - platform: local
        enable-storage: true
        base-path: /file/ # 基础路径
        storage-path: D:/data/files # 存储路径
    # 将 minio访问地址+桶名称 进行组合, 然后设置到 bootx-platform.starter.file-upload.file-server-url
    # 例如 minio地址 http://127.0.0.1:9001  桶名称 daxpay, 拼接后的地址为 http://127.0.0.1:9001/daxpay/
    minio:
      - platform: minio
        enable-storage: true
        access-key: yDAArSoyQAligC2IGf7C
        secret-key: vDgpt5R4kR2UCapMzx32Rb6qZegok21dRsU6XJ1j
        end-point: http://127.0.0.1:9002  # minio访问地址
        bucket-name: daxpay # 存储桶名称
        base-path: /file/ # 基础存储路径
