@startuml
autonumber

actor       客户       as khd
participant 控制器   as kzq
participant 服务类   as fwl
participant DAO   as dao

khd -> kzq: 发送请求
skinparam responseMessageBelowArrow true
kzq --> fwl ++: 组装参数
fwl --> kzq ++: 返回功能
kzq --> fwl --: 继续查询
kzq --> kzq: 继续查询
fwl --> dao ++ : 数据查询
dao --> fwl: 查询
@enduml
