@startuml

map PayOrder {
    名称 => 支付订单
    id => 主键
}
map PayChannelOrder {
    名称 => 通道支付订单
    paymentId => 支付id
}
map PayOrderExtra {
    名称 => 支付订单扩展
    id => 主键
}

map RefundOrder {
    名称 => 退款订单
    id => 主键
    paymentId => 支付id
}

map RefundOrderExtra {
    名称 => 退款订单扩展
    id => 主键
}

map RefundChannelOrder {
    名称 => 通道退款订单
    refundId => 退款id
    payChannelId => 通道支付订单id
}

map AllocationOrder {
    名称 => 分账订单
    paymentId => 支付id
}

map AllocationOrderDetail {
    名称 => 分账订单明细
    allocationId => 分账id
}

'支付订单关联
PayOrder::id <-- PayOrderExtra::id: 一对一关联
PayOrder::id <-- PayChannelOrder::paymentId: 多对一关联

'退款订单
RefundOrder::id <-- RefundOrderExtra::id: 一对一关联
RefundOrder::id <-- RefundChannelOrder::refundId: 多对一关联
RefundOrder::paymentId <-- PayOrder::id: 多对一关联
RefundChannelOrder::payChannelId --> PayChannelOrder::id: 多对一关联

'分账订单
AllocationOrder::paymentId --> PayOrder::id: 多对一关联
AllocationOrder::id --> AllocationOrderDetail::allocationId: 多对一关联


@enduml
