@startuml

object PayOrder
object RefundOrder

map CallbackRecord{
    名称 => 回调记录
    orderId => 订单Id
}

map CloseRecord{
    名称 => 支付订单关闭记录
    paymentId => 支付id
}

map RepairRecord{
    名称 => 修复记录
    orderId => 订单Id(支付/退款)
    repairNo => 修复号(不唯一)
}

map SyncRecord{
    名称 => 同步记录
    orderId => 订单Id(支付/退款)
    repairOrderNo => 修复号
}


'回调记录
CallbackRecord::orderId --> PayOrder::id: 多对一关联
CallbackRecord::orderId --> RefundOrder::id: 多对一关联

'支付订单关闭记录
CloseRecord::paymentId --> PayOrder::id: 一对一关联

'修复记录
RepairRecord::orderId --> PayOrder::id: 多对一关联
RepairRecord::orderId --> RefundOrder::id: 多对一关联

'同步记录
SyncRecord::orderId --> PayOrder::id: 多对一关联
SyncRecord::orderId --> RefundOrder::id: 多对一关联
SyncRecord::repairNo --> RepairRecord::repairNo: 一对一关联

@enduml
