server:
  port: 9000
spring:
  application:
    name: dax-pay-admin
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      # PG逻辑删除需要指定为布尔值, 如果为0/1会出现查询类型错误
      logic-delete-value: true
      logic-not-delete-value: false
