<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.6</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>org.dromara.daxpay</groupId>
    <artifactId>daxpay-open-payment</artifactId>
    <version>3.1.0.beta2</version>
    <packaging>jar</packaging>
    <description>开源版支付核心功能实现</description>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- 三方库 -->
        <mapstruct.version>1.5.5.Final</mapstruct.version>
        <lombok-mapstruct.version>0.2.0</lombok-mapstruct.version>
        <easytrans.version>3.0.5</easytrans.version>
        <wxjava.version>4.7.6.B</wxjava.version>
        <aliyun.ocr.version>3.0.4</aliyun.ocr.version>
        <tencent.cloud.sdk.ocr>3.1.1270</tencent.cloud.sdk.ocr>

        <bootx-platform.version>3.1.0.beta2</bootx-platform.version>
        <daxpay.version>3.1.0.beta2</daxpay.version>
    </properties>

    <dependencies>
        <!-- lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- lombok 配合 mapstruct -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok-mapstruct-binding</artifactId>
            <scope>provided</scope>
            <version>${lombok-mapstruct.version}</version>
        </dependency>

        <!-- 类型转换处理器 -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <scope>provided</scope>
            <version>${mapstruct.version}</version>
        </dependency>

        <!-- 测试包 -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- web框架 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- 校验注解包 -->
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>

        <!-- 类型转换 -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>

        <!-- javaEE web相关 -->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>

        <!-- 临时依赖, 后期会重新整理 -->

        <!-- platform核心包 -->
        <dependency>
            <groupId>cn.bootx.platform</groupId>
            <artifactId>bootx-platform-core</artifactId>
            <version>${bootx-platform.version}</version>
        </dependency>
        <!-- 延时任务 -->
        <dependency>
            <groupId>cn.bootx.platform</groupId>
            <artifactId>starter-delay-queue</artifactId>
            <version>${bootx-platform.version}</version>
        </dependency>
        <!-- swagger -->
        <dependency>
            <groupId>cn.bootx.platform</groupId>
            <artifactId>common-swagger</artifactId>
            <version>${bootx-platform.version}</version>
        </dependency>
        <!-- 认证服务 -->
        <dependency>
            <groupId>cn.bootx.platform</groupId>
            <artifactId>service-iam</artifactId>
            <version>${bootx-platform.version}</version>
        </dependency>



        <!-- 微信工具包 -->
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-mp</artifactId>
            <version>${wxjava.version}</version>
        </dependency>
        <!-- 阿里云OCR -->
        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>alibabacloud-ocr_api20210707</artifactId>
            <version>${aliyun.ocr.version}</version>
        </dependency>
        <!-- 腾讯云OCR -->
        <dependency>
            <groupId>com.tencentcloudapi</groupId>
            <artifactId>tencentcloud-sdk-java-ocr</artifactId>
            <version>${tencent.cloud.sdk.ocr}</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <!-- 打包Excel等资源文件损坏问题 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>xlsx</nonFilteredFileExtension>
                        <nonFilteredFileExtension>xls</nonFilteredFileExtension>
                        <nonFilteredFileExtension>docx</nonFilteredFileExtension>
                        <nonFilteredFileExtension>doc</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <!-- 指定打包资源路径 -->
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*</include>
                </includes>
            </resource>
            <!-- java类路径中会被打包的软件 -->
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                    <include>**/*.sql</include>
                    <include>**/*.flt</include>
                    <include>**/*.xlsx</include>
                    <include>**/*.xls</include>
                    <include>**/*.docx</include>
                    <include>**/*.doc</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>
