<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.daxpay.open</groupId>
        <artifactId>daxpay</artifactId>
        <version>4.0.0-beta3</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>daxpay-payment</artifactId>
    <packaging>pom</packaging>
    <description>多商户支付功能（core 内核 + admin/app-admin/merchant/unipay 按端 HTTP）</description>

    <modules>
        <module>daxpay-payment-core</module>
        <module>daxpay-payment-admin</module>
        <module>daxpay-payment-app-admin</module>
        <module>daxpay-payment-app-merchant</module>
        <module>daxpay-payment-unipay</module>
        <module>daxpay-payment-merchant</module>
    </modules>

</project>
