<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>cn.daxpay.open</groupId>
        <artifactId>daxpay-platform</artifactId>
        <version>4.0.0-beta3</version>
    </parent>
    <modules>
        <module>capability-auth</module>
        <module>capability-audit-log</module>
        <module>capability-file</module>
        <module>capability-cache</module>
        <module>capability-nonce</module>
        <module>capability-wechat</module>
        <module>capability-social</module>
        <module>capability-alipay</module>
        <module>capability-douyin</module>
        <module>capability-sensitive-word</module>
    </modules>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>daxpay-platform-capability</artifactId>
    <packaging>pom</packaging>

    <dependencies>
        <!-- 核心包 -->
        <dependency>
            <groupId>cn.daxpay.open</groupId>
            <artifactId>daxpay-platform-core</artifactId>
            <version>4.0.0-beta3</version>
        </dependency>
        <!-- lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- 类型转换处理器 -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <scope>provided</scope>
            <version>${mapstruct.version}</version>
        </dependency>

        <!-- 类型转换 -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>

    </dependencies>

</project>
