server:
  port: 8888
spring:
  application:
    name: dax-pay-gateway
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      # PG逻辑删除需要指定为布尔值, 如果为0/1会出现查询类型错误
      logic-delete-value: true
      logic-not-delete-value: false
mybatis-plus-join:
  banner: false
sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  is-log: false
  is-print: false
# 平台配置
bootx-platform:
  config:
    client-code: dax-pay-gateway
